COLORS = [
    "#EF4444", # Red 500
    "#3B82F6", # Blue 500
    "#10B981", # Emerald 500
    "#F59E0B", # Amber 500
    "#8B5CF6", # Violet 500
    "#EC4899", # Pink 500
    "#06B6D4", # Cyan 500
    "#84CC16", # Lime 500
    "#F97316", # Orange 500
    "#14B8A6", # Teal 500
    "#6366F1", # Indigo 500
    "#D946EF", # Fuchsia 500
    "#F43F5E", # Rose 500
    "#0EA5E9", # Sky 500
    "#22C55E", # Green 500
    "#EAB308", # Yellow 500
    "#A855F7", # Purple 500
    "#64748B", # Slate 500
    "#A1A1AA", # Zinc 400
    "#FB7185", # Rose 400
]

LANGUAGE_METADATA = {
    "English": "🇺🇸 English",
    "Ukrainian": "🇺🇦 Українська"
}

WORD_SETS = {
    "English": {
        "Easy": [
            "Sun", "Moon", "Star", "Tree", "Flower", "House", "Car", "Cat", "Dog", "Book",
            "Apple", "Ball", "Banana", "Bed", "Bird", "Blue", "Boat", "Box", "Boy", "Bread",
            "Bus", "Cake", "Candy", "Carrot", "Chair", "Cheese", "Chicken", "Clock", "Cloud", "Coat",
            "Cow", "Cup", "Desk", "Door", "Dress", "Duck", "Ear", "Egg", "Eye", "Face",
            "Farm", "Fish", "Flag", "Floor", "Foot", "Fork", "Fox", "Frog", "Game", "Garden",
            "Girl", "Glass", "Glove", "Goat", "Gold", "Grass", "Hair", "Hand", "Hat", "Head",
            "Heart", "Horse", "Ice", "Key", "King", "Kite", "Lamp", "Leaf", "Leg", "Lemon",
            "Lion", "Lock", "Map", "Milk", "Mouse", "Mouth", "Nail", "Neck", "Nest", "Night",
            "Nose", "Orange", "Owl", "Pan", "Pen", "Pig", "Pin", "Pink", "Pipe", "Plate",
            "Pot", "Queen", "Rabbit", "Rain", "Rat", "Ring", "Road", "Roof", "Room", "Rose",
            "Rug", "Run", "Salt", "Sand", "Sea", "Sheep", "Ship", "Shoe", "Shop", "Sky",
            "Snow", "Sock", "Song", "Spoon", "Star", "Stick", "Stone", "Stop", "Store", "Street",
            "Sugar", "Table", "Tail", "Tap", "Tea", "Tent", "Time", "Toe", "Town", "Toy",
            "Train", "Tree", "Truck", "Walk", "Wall", "Water", "Way", "Wind", "Window", "Wing",
            "Wolf", "Wood", "Wool", "Word", "Work", "Yard", "Year", "Zoo", "Ant", "Arm",
            "Baby", "Bag", "Bath", "Bear", "Bee", "Bell", "Belt", "Bike", "Boat", "Bone",
            "Bowl", "Brush", "Cage", "Card", "Cart", "Case", "Chain", "Chin", "City", "Club",
            "Coal", "Coin", "Comb", "Cook", "Cord", "Cork", "Corn", "Crab", "Crow", "Date",
            "Deer", "Dish", "Doll", "Drum", "Dust", "East", "Edge", "Fan", "Feet", "Fire",
            "Fly", "Foam", "Food", "Frog", "Gate", "Gift", "Gold", "Golf", "Goose", "Grain",
            "Hair", "Hall", "Hare", "Harp", "Hawk", "Hay", "Heel", "Hill", "Hoe", "Hole",
            "Hook", "Horn", "Hose", "Hour", "Ink", "Iron", "Jack", "Jam", "Jar", "Jaw",
            "Jay", "Jelly", "Jet", "Joke", "Jug", "Kale", "Kelp", "Kick", "Kid", "Kiss",
            "Kite", "Knee", "Knot", "Lace", "Lady", "Lake", "Lamb", "Lamp", "Land", "Lark",
            "Lead", "Leaf", "Leek", "Lid", "Life", "Lift", "Lime", "Line", "Link", "Lion",
            "Lip", "List", "Load", "Loaf", "Lock", "Log", "Loop", "Lord", "Love", "Luck",
            "Lung", "Lynx", "Maid", "Mail", "Mall", "Man", "Map", "Mark", "Mask", "Mass",
            "Mat", "Meal", "Meat", "Melt", "Mesh", "Mess", "Mice", "Milk", "Mill", "Mind",
            "Mine", "Mink", "Mint", "Mist", "Mole", "Monk", "Mood", "Moon", "Moss", "Moth",
            "Move", "Mug", "Mule", "Music", "Name", "Navy", "Neck", "Need", "Nest", "Net",
            "News", "Node", "Noise", "Noun", "Nun", "Nut", "Oak", "Oar", "Oat", "Oil",
            "One", "Ox", "Pack", "Page", "Pail", "Pain", "Pair", "Palm", "Pan", "Park",
            "Part", "Pass", "Past", "Path", "Pea", "Peak", "Pear", "Pen", "Pet", "Pie",
            "Pig", "Pin", "Pine", "Pipe", "Pit", "Plan", "Play", "Plow", "Plug", "Plum",
            "Poet", "Point", "Pole", "Poll", "Pond", "Pool", "Pop", "Post", "Pot", "Prop",
            "Pump", "Pup", "Push", "Quail", "Queen", "Quit", "Quiz", "Raft", "Rail", "Rain",
            "Rake", "Rat", "Ray", "Red", "Reed", "Reel", "Rent", "Rest", "Rib", "Rice",
            "Rich", "Ride", "Rim", "Ring", "Rink", "Risk", "Road", "Robe", "Rock", "Rod",
            "Role", "Roof", "Room", "Root", "Rope", "Rose", "Row", "Rub", "Rug", "Rule",
            "Run", "Rust", "Rye", "Sack", "Safe", "Sail", "Salt", "Sand", "Sash", "Save",
            "Saw", "Sea", "Seal", "Seat", "Seed", "Seek", "Self", "Send", "Set", "Sew",
            "Shape", "Sheep", "Sheet", "Shell", "Ship", "Shirt", "Shoe", "Shop", "Shot", "Show",
            "Shut", "Side", "Sign", "Silk", "Sill", "Sink", "Site", "Size", "Skin", "Skip",
            "Skirt", "Sky", "Sled", "Slip", "Slot", "Slug", "Smile", "Smoke", "Snail", "Snake",
            "Snap", "Snow", "Soap", "Sock", "Soda", "Sofa", "Soft", "Soil", "Sold", "Sole",
            "Son", "Song", "Sort", "Soul", "Soup", "Sow", "Spa", "Space", "Spade", "Span",
            "Spark", "Spear", "Speed", "Spell", "Spice", "Spin", "Spit", "Spot", "Spray", "Spur",
            "Spy", "Square", "Stage", "Stair", "Stamp", "Stand", "Star", "Stare", "Start", "State",
            "Stay", "Steam", "Steel", "Stem", "Step", "Stew", "Stick", "Sting", "Stir", "Stock",
            "Stone", "Stop", "Store", "Storm", "Story", "Stove", "Straw", "Stream", "Street", "String",
            "Strip", "Study", "Stuff", "Stump", "Style", "Suit", "Summer", "Sun", "Surf", "Swan",
            "Swim", "Swing", "Switch", "Sword", "Table", "Tack", "Tag", "Tail", "Talk", "Tall",
            "Tank", "Tap", "Tape", "Tar", "Tart", "Task", "Taste", "Tax", "Tea", "Team",
            "Tear", "Teeth", "Tell", "Tent", "Term", "Test", "Text", "Thaw", "Thing", "Think",
            "Thin", "Thong", "Thorn", "Thread", "Thumb", "Tick", "Tie", "Tiger", "Tile", "Till",
            "Time", "Tin", "Tip", "Tire", "Title", "Toad", "Toast", "Toe", "Toil", "Token",
            "Toll", "Tone", "Tool", "Tooth", "Top", "Torch", "Toss", "Touch", "Tour", "Towel",
            "Tower", "Town", "Toy", "Track", "Trade", "Trail", "Train", "Tram", "Trap", "Tray",
            "Tree", "Trek", "Trick", "Trip", "Troop", "Truck", "True", "Tube", "Tub", "Tug",
            "Tune", "Turf", "Turn", "Tusk", "Twin", "Type", "Unit", "Urn", "Use", "Van",
            "Vase", "Veil", "Vein", "Vent", "Verb", "Vest", "Vet", "Vice", "View", "Vine",
            "Voice", "Void", "Volt", "Vote", "Vow", "Wage", "Wagon", "Waist", "Wait", "Wake",
            "Walk", "Wall", "Wand", "Want", "War", "Ward", "Warm", "Warn", "Warp", "Wash",
            "Wasp", "Watch", "Water", "Wave", "Wax", "Way", "Weak", "Wealth", "Wear", "Web",
            "Wedge", "Weed", "Week", "Well", "West", "Wet", "Whale", "Wharf", "Wheat", "Wheel",
            "Whip", "White", "Whole", "Wick", "Wife", "Wig", "Wild", "Will", "Wind", "Wine",
            "Wing", "Wink", "Wire", "Wise", "Wish", "Wit", "Wolf", "Wood", "Wool", "Word",
            "Work", "Worm", "Wrap", "Wren", "Wrist", "Write", "Wrong", "Yard", "Yarn", "Year",
            "Yell", "Yellow", "Yelp", "Yolk", "Zone", "Zoo",
             # Adding more to reach closer to target
            "Camera", "Radio", "Video", "Piano", "Violin", "Guitar", "Flute", "Drum", "Trumpet",
            "Pencil", "Eraser", "Ruler", "Paper", "Folder", "Notebook", "School", "Teacher", "Student",
            "Doctor", "Nurse", "Police", "Fireman", "Artist", "Baker", "Cook", "Driver", "Farmer",
            "Panda", "Koala", "Zebra", "Camel", "Monkey", "Gorilla", "Shark", "Whale", "Dolphin",
            "Eagle", "Parrot", "Pigeon", "Turkey", "Penguin", "Ostrich", "Spider", "Snake", "Lizard",
            "Turtle", "Rabbit", "Mouse", "Hamster", "Puppy", "Kitten", "Horse", "Sheep", "Goat",
            "Table", "Chair", "Sofa", "Bed", "Lamp", "Rug", "Curtain", "Door", "Window",
            "Kitchen", "Bedroom", "Bathroom", "Garage", "Garden", "Fence", "Gate", "Path", "Tree"
        ],
        "Medium": [
            "Bicycle", "Apple", "Banana", "Grapes", "Orange", "Lion", "Tiger", "Bear", "Elephant", "Giraffe",
            "Pilot", "Plumber", "Waiter", "Actor", "Judge", "Lawyer", "Guard", "Chief", "Coach", "Guide",
            "Airport", "Station", "Market", "Bridge", "Cinema", "Hotel", "Museum", "Palace", "Prison", "School",
            "Tennis", "Soccer", "Hockey", "Rugby", "Golf", "Skiing", "Boxing", "Judo", "Bingo", "Chess",
            "Apricot", "Avocado", "Cherry", "Coconut", "Fig", "Kiwi", "Lemon", "Mango", "Melon", "Olive",
            "Peach", "Pear", "Plum", "Berry", "Tomato", "Carrot", "Onion", "Potato", "Corn", "Peas",
            "Winter", "Spring", "Summer", "Autumn", "Storm", "Thunder", "Cloud", "Rain", "Snow", "Wind",
            "Monday", "Friday", "Sunday", "April", "August", "Month", "Week", "Year", "Hour", "Minute",
            "Circle", "Square", "Star", "Heart", "Cross", "Line", "Point", "Shape", "Angle", "Curve",
            "Anchor", "Anvil", "Arch", "Arrow", "Atom", "Badge", "Bagel", "Banjo", "Baron", "Basin",
            "Batch", "Baton", "Beaker", "Beard", "Beast", "Beetle", "Bench", "Berry", "Biscuit", "Blade",
            "Bleach", "Blind", "Bliss", "Block", "Blood", "Bloom", "Board", "Boast", "Bobby", "Boiler",
            "Bonus", "Boost", "Booth", "Booty", "Border", "Botany", "Bottle", "Bottom", "Bough", "Bounty",
            "Bowel", "Brace", "Brain", "Brake", "Brand", "Brass", "Brave", "Breadth", "Break", "Breast",
            "Breed", "Breeze", "Brew", "Bribe", "Brick", "Bride", "Bridge", "Brief", "Brine", "Broad",
            "Broil", "Bronze", "Brook", "Broom", "Broth", "Brown", "Bruise", "Brush", "Brute", "Bubble",
            "Bucket", "Buckle", "Budget", "Buffer", "Buffet", "Buggy", "Bulb", "Bulge", "Bullet", "Bunch",
            "Bunny", "Bureau", "Burial", "Burner", "Bushel", "Butler", "Butter", "Button", "Buyer", "Cabin",
            "Cable", "Cactus", "Caddy", "Cadet", "Camel", "Camera", "Canal", "Canary", "Candid", "Candle",
            "Canoe", "Canopy", "Canton", "Canvas", "Canyon", "Capital", "Carat", "Carbon", "Cargo", "Carol",
            "Carpet", "Carton", "Carve", "Castle", "Casual", "Cattle", "Cause", "Cedar", "Cellar", "Cement",
            "Census", "Cereal", "Chain", "Chalk", "Chant", "Chaos", "Chapel", "Charm", "Chart", "Chase",
            "Chasm", "Cheap", "Cheat", "Check", "Cheek", "Cheer", "Cheese", "Cherry", "Chest", "Chick",
            "Chief", "Child", "Chill", "Chime", "China", "Chip", "Choir", "Choke", "Chord", "Chore",
            "Chunk", "Churn", "Chute", "Cider", "Cigar", "Cinch", "Circle", "Circus", "Civil", "Claim",
            "Clamp", "Clam", "Clang", "Clank", "Clash", "Clasp", "Class", "Clause", "Claw", "Clay",
            "Clean", "Clear", "Cleat", "Cleft", "Clerk", "Click", "Cliff", "Climb", "Clinic", "Cloak",
            "Clock", "Clod", "Clog", "Close", "Cloth", "Cloud", "Clout", "Clove", "Clown", "Club",
            "Cluck", "Clump", "Coach", "Coast", "Cobweb", "Cocoa", "Coffee", "Coil", "Coin", "Cold",
            "Collar", "Colon", "Color", "Colt", "Comb", "Come", "Comet", "Comic", "Comma", "Conch",
            "Cone", "Cook", "Cool", "Coop", "Cope", "Copper", "Copy", "Coral", "Cord", "Core",
            "Cork", "Corn", "Corner", "Corpse", "Cost", "Couch", "Cough", "Count", "Coupe", "Coupon",
            "Court", "Cover", "Coward", "Crab", "Crack", "Craft", "Crane", "Crank", "Crash", "Crate",
            "Crawl", "Craze", "Crazy", "Cream", "Create", "Credit", "Creek", "Creep", "Crest", "Crew",
            "Crib", "Crime", "Crisp", "Critic", "Croak", "Crock", "Crook", "Crop", "Cross", "Crowd",
            "Crown", "Crude", "Cruel", "Cruise", "Crumb", "Crush", "Crust", "Crutch", "Crypt", "Cube",
            "Cuckoo", "Cuff", "Cult", "Cupid", "Curb", "Cure", "Curio", "Curl", "Curry", "Curse",
            "Curve", "Cycle", "Cynic", "Dairy", "Daisy", "Dance", "Dandy", "Danger", "Daring", "Dark",
            "Dart", "Dash", "Data", "Date", "Dawn", "Daze", "Dead", "Deaf", "Deal", "Dean",
            "Dear", "Debate", "Debit", "Debt", "Debut", "Decade", "Decay", "Deck", "Decor", "Decoy",
            "Deed", "Deep", "Deer", "Defeat", "Defect", "Degree", "Delay", "Delight", "Dell", "Delta",
            "Demand", "Demon", "Denim", "Dent", "Depot", "Depth", "Deputy", "Derby", "Desert", "Design",
            "Desire", "Desk", "Detail", "Detect", "Device", "Devil", "Dial", "Diary", "Dice", "Diet",
            "Digit", "Dine", "Dinghy", "Dinner", "Diode", "Dirt", "Disc", "Dish", "Disk", "Ditch",
            "Ditty", "Divan", "Diver", "Dock", "Doctor", "Dodge", "Dogma", "Doily", "Doing", "Dollar",
            "Dolly", "Dolphin", "Domain", "Dome", "Donor", "Doom", "Door", "Dope", "Dose", "Dot",
            "Double", "Doubt", "Dough", "Dove", "Down", "Dozen", "Draft", "Drag", "Drain", "Drake",
            "Drama", "Drape", "Draw", "Dread", "Dream", "Dress", "Drift", "Drill", "Drink", "Drip",
            "Drive", "Drone", "Drop", "Drove", "Drug", "Drum", "Drunk", "Dryer", "Dual", "Duck",
            "Duct", "Duel", "Duet", "Duke", "Dull", "Dummy", "Dump", "Dune", "Dung", "Dusk",
            "Dust", "Dutch", "Duty", "Dwarf", "Dwelling", "Dye", "Dying", "Dynamo", "Eagle", "Earl",
            "Early", "Earth", "Ease", "Easel", "Easter", "Eating", "Ebony", "Echo", "Eclipse", "Edge",
            "Editor", "Effect", "Effort", "Egg", "Eight", "Eject", "Elbow", "Elder", "Elect", "Elegy",
            "Element", "Elephant", "Eleven", "Elf", "Elite", "Elk", "Elm", "Emblem", "Embryo", "Emery",
            "Emotion", "Empire", "Empty", "Enamel", "End", "Enemy", "Energy", "Engine", "Enjoy", "Ensign",
            "Enter", "Entry", "Envoy", "Envy", "Epic", "Epoch", "Equal", "Equator", "Era", "Eraser",
            "Error", "Essay", "Estate", "Ether", "Ethic", "Ethnic", "Event", "Evil", "Exam", "Exit",
            "Expert", "Export", "Eye", "Fable", "Face", "Fact", "Factor", "Fade", "Fail", "Faint",
            "Fair", "Fairy", "Faith", "Fake", "Falcon", "Fall", "False", "Fame", "Family", "Famine",
            "Fan", "Fancy", "Fang", "Farce", "Farm", "Fast", "Fat", "Fate", "Father", "Faucet",
            "Fault", "Favor", "Fawn", "Fear", "Feast", "Feat", "Feel", "Feet", "Felon", "Felt",
            "Female", "Fence", "Ferry", "Fetch", "Fetus", "Fever", "Fiber", "Fibre", "Fiddle", "Field",
            "Fiend", "Fifer", "Fifty", "Fig", "Fight", "Figure", "File", "Fill", "Film", "Filter",
            "Filth", "Final", "Finance", "Find", "Fine", "Finger", "Finish", "Fire", "Firm", "First",
            "Fish", "Fist", "Five", "Fix", "Flag", "Flail", "Flair", "Flake", "Flame", "Flank",
            "Flare", "Flash", "Flask", "Flat", "Flavor", "Flaw", "Flea", "Fleck", "Fleet", "Flesh",
            "Flex", "Flick", "Flight", "Flint", "Flip", "Flirt", "Float", "Flock", "Flood", "Floor",
            "Flop", "Flora", "Floss", "Flour", "Flow", "Flower", "Fluent", "Fluff", "Fluid", "Flush",
            "Flute", "Fly", "Foam", "Focal", "Focus", "Fog", "Ffoil"
        ],
        "Hard": [
            "Computer", "Phone", "Clock", "Watch", "Glasses", "Submarine", "Helicopter", "Rocket", "Spaceship", "Parachute",
            "Algorithm", "Backpack", "Bandage", "Battery", "Biscuit", "Blanket", "Blender", "Blouse", "Bucket", "Button",
            "Cabinet", "Cactus", "Camera", "Candle", "Canvas", "Carpet", "Carrot", "Castle", "Ceiling", "Cement",
            "Ceramic", "Channel", "Circle", "Circus", "Client", "Climate", "Closet", "Coffee", "Coffin", "Collar",
            "Comedy", "Comfort", "Commit", "Common", "Compass", "Concert", "Concept", "Concrete", "Conduct", "Conflict",
            "Congress", "Context", "Control", "Convert", "Corner", "Cotton", "Council", "Counter", "Country", "Couple",
            "Courage", "Course", "Cousin", "Credit", "Cricket", "Crystal", "Culture", "Curtain", "Cushion", "Custom",
            "Damage", "Danger", "Dealer", "Debate", "Decade", "Degree", "Demand", "Design", "Detail", "Device",
            "Diamond", "Digest", "Dinner", "Direct", "Doctor", "Dollar", "Domain", "Donkey", "Double", "Dragon",
            "Drawer", "Drawing", "Driver", "Eagerness", "Edition", "Effect", "Effort", "Eighth", "Elastic", "Election",
            "Element", "Embassy", "Emotion", "Empire", "Engine", "Enough", "Entity", "Entrance", "Episode", "Equator",
            "Essence", "Estate", "Evening", "Evidence", "Example", "Exchange", "Excuse", "Exhibit", "Expense", "Expert",
            "Express", "Extend", "Fabric", "Factor", "Factory", "Failure", "Family", "Famous", "Fantasy", "Farmer",
            "Fashion", "Father", "Fatigue", "Faucet", "Feature", "Federal", "Feeling", "Fellow", "Fender", "Fiction",
            "Figure", "Filter", "Finance", "Finish", "Fireman", "Fiscal", "Fishing", "Fitness", "Flavor", "Flight",
            "Flower", "Flying", "Follow", "Forest", "Formal", "Format", "Former", "Formula", "Fortune", "Forward",
            "Founder", "Fourth", "Fragile", "Fragment", "Freedom", "Freezer", "Freight", "French", "Friend", "Fringe",
            "Frozen", "Frying", "Function", "Funeral", "Furnace", "Future", "Gallery", "Gallon", "Garage", "Garbage",
            "Garden", "Garlic", "Gather", "Gender", "General", "Genius", "Gentle", "German", "Gesture", "Gigantic",
            "Giggle", "Ginger", "Giraffe", "Glacier", "Glamour", "Glance", "Glasses", "Global", "Glucose", "Golden",
            "Gospel", "Gossip", "Govern", "Gradual", "Grammar", "Grandpa", "Granny", "Grapes", "Graphic", "Gravel",
            "Gravy", "Grease", "Greater", "Green", "Grocery", "Ground", "Group", "Growth", "Guilt", "Guitar",
            "Habit", "Hammer", "Hamster", "Handful", "Handle", "Hanger", "Happen", "Harbor", "Hardly", "Harvest",
            "Hazard", "Health", "Heaven", "Height", "Helmet", "Helper", "Herbal", "Heroic", "Hidden", "High",
            "Highlight", "Highway", "Hiking", "History", "Hockey", "Holder", "Hollow", "Honest", "Honey", "Honor",
            "Horror", "Horse", "Hospital", "Hostel", "Hotel", "Huddle", "Humane", "Human", "Humble", "Humidity",
            "Humor", "Hunger", "Hunter", "Hurdle", "Husband", "Hybrid", "Hygiene", "Hyphen", "Iceberg", "Icicle",
            "Icon", "Idea", "Ideal", "Idiom", "Igloo", "Ignore", "Image", "Impact", "Import", "Income",
            "Index", "Indoor", "Induce", "Infant", "Infect", "Infer", "Influx", "Inform", "Injury", "Inner",
            "Input", "Insect", "Inside", "Insult", "Insure", "Intact", "Intent", "Invent", "Invest", "Invite",
            "Irony", "Island", "Issue", "Ivory", "Jacket", "Jaguar", "Jargon", "Jasmine", "Jasper", "Javelin",
            "Jawbone", "Jealous", "Jersey", "Jewel", "Jigsaw", "Jingle", "Jockey", "Jogging", "Journal", "Journey",
            "Jovial", "Joyful", "Judged", "Judicial", "Juggler", "Juice", "Jumble", "Jumper", "Jungle", "Junior",
            "Jupiter", "Justice", "Justify", "Karma", "Kayak", "Keeper", "Kennel", "Kettle", "Keypad", "Khaki",
            "Kidnap", "Kidney", "Killer", "Killing", "Kindle", "Kingdom", "Kiosk", "Kitten", "Knack", "Knapsack",
            "Knight", "Knitting", "Knock", "Koala", "Label", "Labor", "Ladder", "Lagoon", "Lamb", "Land",
            "Landing", "Lantern", "Laptop", "Large", "Laser", "Lately", "Latent", "Latest", "Lathe", "Latin",
            "Latter", "Laugh", "Launch", "Laundry", "Laurel", "Lavender", "Lavish", "Lawful", "Lawsuit", "Lawyer",
            "Layout", "Leader", "League", "Leaky", "Learn", "Lease", "Leather", "Leave", "Lecture", "Ledger",
            "Legend", "Legion", "Lemon", "Length", "Lens", "Leopard", "Lesson", "Lethal", "Letter", "Level",
            "Lever", "Liable", "Liar", "Libel", "Liber", "Libido", "Library", "Licence", "License", "Lichen",
            "Light", "Likely", "Lilac", "Limit", "Linen", "Linger", "Linguist", "Lining", "Linked", "Linnet",
            "Liquid", "Liquor", "Listen", "Literal", "Lithium", "Litter", "Little", "Lively", "Liver", "Living",
            "Lizard", "Llama", "Loading", "Loathe", "Lobby", "Lobster", "Local", "Locate", "Lockup", "Locust",
            "Lodge", "Logbook", "Logger", "Logic", "Lonely", "Longer", "Lookout", "Loosen", "Looter", "Lord",
            "Lorry", "Loser", "Losing", "Lotion", "Lottery", "Lotus", "Louder", "Lounge", "Louse", "Lousy",
            "Lover", "Lower", "Loyal", "Lucid", "Lucky", "Lumber", "Lumpy", "Lunacy", "Lunar", "Lunch",
            "Lung", "Lurch", "Lure", "Lurid", "Lurk", "Luster", "Luxury", "Lyric", "Machine", "Macro",
            "Madam", "Madly", "Mafia", "Magic", "Magma", "Magnet", "Magpie", "Maiden", "Mailbox", "Mainly",
            "Major", "Maker", "Makeup", "Mambo", "Mammal", "Manage", "Manes", "Manger", "Mania", "Manic",
            "Manor", "Mantle", "Manual", "Manure", "Maple", "Marble", "March", "Margin", "Marina", "Marine",
            "Marker", "Market", "Marlin", "Marrow", "Marsh", "Marten", "Martin", "Martyr", "Marvel", "Mascot",
            "Mason", "Masque", "Masses", "Master", "Mastic", "Match", "Mate", "Matrix", "Matron", "Matter",
            "Mature", "Maxim", "Mayor", "Meadow", "Meager", "Meaning", "Measles", "Measure", "Meatball", "Mecanic",
            "Medal", "Media", "Medic", "Medium", "Medley", "Mellow", "Melody", "Melon", "Member", "Memory",
            "Menace", "Mending", "Menial", "Mental", "Mentor", "Mercy", "Merger", "Merit", "Merry", "Message",
            "Metal", "Meteor", "Meter", "Method", "Metric", "Metro", "Micro", "Midday", "Middle", "Midget",
            "Midnight", "Midst", "Might", "Mighty", "Migrant", "Mildew", "Mileage", "Milkman", "Million", "Mimic",
            "Mince", "Minden", "Miner", "Mingle", "Minim", "Mining", "Minor", "Minty", "Minus", "Minute",
            "Miracle", "Mirror", "Mischief", "Miser", "Missile", "Mission", "Mistake", "Mister", "Mistress", "Misty",
            "Mitten", "Mixing", "Mixture", "Mobile", "Model", "Modem", "Modern", "Modest", "Modify", "Module",
            "Mohair", "Moist", "Molar", "Molding", "Molecule", "Moment", "Monarch", "Money", "Monitor", "Monkey",
            "Mono", "Monster", "Month", "Monument", "Mood", "Moonlit", "Moral", "Morale", "Morbid", "Morgue",
            "Morning", "Moron", "Mortal", "Mortar", "Mosaic", "Mosque", "Mossy", "Most", "Motel", "Moth",
            "Mother", "Motion", "Motive", "Motor", "Motto", "Mound", "Mount", "Mourn", "Mouse", "Mouth",
            "Movement", "Movie", "Moving", "Mower", "Mucus", "Muddy", "Muffin", "Muffle", "Muggy", "Mulch"
        ]
    },
    "Ukrainian": {
        "Легкі": [
            "Сонце", "Місяць", "Зірка", "Дерево", "Квітка", "Хата", "Машина", "Кіт", "Собака", "Книга",
            "Яблуко", "М'яч", "Банан", "Ліжко", "Птах", "Синій", "Човен", "Коробка", "Хлопчик", "Хліб",
            "Автобус", "Торт", "Цукерка", "Морква", "Стілець", "Сир", "Курка", "Годинник", "Хмара", "Пальто",
            "Корова", "Чашка", "Стіл", "Двері", "Сукня", "Качка", "Вухо", "Яйце", "Око", "Обличчя",
            "Ферма", "Риба", "Прапор", "Підлога", "Нога", "Виделка", "Лисиця", "Жаба", "Гра", "Сад",
            "Дівчина", "Скло", "Рукавичка", "Коза", "Золото", "Трава", "Волосся", "Рука", "Капелюх", "Голова",
            "Серце", "Кінь", "Лід", "Ключ", "Король", "Повітряний змій", "Лампа", "Лист", "Лимон",
            "Лев", "Замок", "Карта", "Молоко", "Миша", "Рот", "Цвях", "Шия", "Гніздо", "Ніч",
            "Ніс", "Апельсин", "Сова", "Сковорода", "Ручка", "Свиня", "Шпилька", "Рожевий", "Труба", "Тарілка",
            "Горщик", "Королева", "Кролик", "Дощ", "Щур", "Кільце", "Дорога", "Дах", "Кімната", "Троянда",
            "Килим", "Бігти", "Сіль", "Пісок", "Море", "Вівця", "Корабель", "Взуття", "Магазин", "Небо",
            "Сніг", "Шкарпетка", "Пісня", "Ложка", "Палиця", "Камінь", "Стоп", "Вулиця",
            "Цукор", "Хвіст", "Кран", "Чай", "Намет", "Час", "Палець", "Місто", "Іграшка",
            "Поїзд", "Ліс", "Вантажівка", "Гуляти", "Стіна", "Вода", "Шлях", "Вітер", "Вікно", "Крило",
            "Вовк", "Деревина", "Вовна", "Слово", "Робота", "Двір", "Рік", "Зоопарк", "Мураха",
            "Дитина", "Сумка", "Ванна", "Ведмідь", "Бджола", "Дзвін", "Ремінь", "Велосипед", "Кістка",
            "Миска", "Щітка", "Клітка", "Листівка", "Візок", "Валіза", "Ланцюг", "Підборіддя", "Клуб",
            "Вугілля", "Монета", "Гребінець", "Кухар", "Шнур", "Корок", "Кукурудза", "Краб", "Ворона", "Фінік",
            "Олень", "Страва", "Лялька", "Барабан", "Пил", "Схід", "Край", "Вентилятор", "Ноги", "Вогонь",
            "Муха", "Піна", "Їжа", "Ворота", "Подарунок", "Гольф", "Гусак", "Зерно",
            "Зал", "Заєць", "Арфа", "Яструб", "Сіно", "П'ята", "Пагорб", "Мотыга", "Яма",
            "Гак", "Ріг", "Шланг", "Година", "Чорнило", "Праска", "Валет", "Джем", "Бак", "Щелепа",
            "Сойка", "Желе", "Літак", "Жарт", "Глечик", "Капуста", "Водорості", "Удар", "Поцілунок",
            "Коліно", "Вузол", "Мереживо", "Леді", "Озеро", "Ягня", "Земля", "Жайворонка",
            "Свинець", "Цибуля-порей", "Кришка", "Життя", "Ліфт", "Лайм", "Лінія", "Ланка",
            "Губа", "Список", "Вантаж", "Буханець", "Колода", "Петля", "Лорд", "Любов", "Удача",
            "Легені", "Рись", "Покоївка", "Пошта", "Торговий центр", "Чоловік", "Знак", "Маска", "Маса",
            "Килимок", "Страва", "М'ясо", "Танення", "Сітка", "Безлад", "Мозок",
            "Шахта", "Норка", "М'ята", "Туман", "Кріт", "Чернець", "Настрій", "Мох", "Міль",
            "Рух", "Кружка", "Мул", "Музика", "Ім'я", "Флот", "Потреба", "Сітка",
            "Новини", "Вузол", "Шум", "Іменник", "Черниця", "Горіх", "Дуб", "Весло", "Овес", "Олія",
            "Один", "Віл", "Пакет", "Сторінка", "Відро", "Біль", "Пара", "Пальма", "Парк",
            "Частина", "Пропуск", "Минуле", "Стежка", "Горох", "Вершина", "Груша", "Тварина", "Пиріг",
            "Сосна", "Яма", "План", "Грати", "Плуг", "Вилка", "Слива",
            "Поет", "Точка", "Полюс", "Опитування", "Ставок", "Басейн", "Поп", "Пост", "Опора",
            "Насос", "Цуценя", "Поштовх", "Перепілка", "Вихід", "Вікторина", "Пліт", "Рейка",
            "Граблі", "Промінь", "Червоний", "Тростина", "Котушка", "Оренда", "Відпочинок", "Ребро", "Рис",
            "Багатий", "Їзда", "Обід", "Ковзанка", "Ризик", "Халат", "Скеля", "Стрижень",
            "Роль", "Корінь", "Мотузка", "Ряд", "Терти", "Правило",
            "Іржа", "Жито", "Мішок", "Сейф", "Вітрило", "Пояс", "Зберегти",
            "Пила", "Тюлень", "Сидіння", "Насіння", "Шукати", "Я", "Надіслати", "Набір", "Шити",
            "Форма", "Аркуш", "Мушля", "Сорочка", "Постріл", "Шоу",
            "Закрити", "Бік", "Шовк", "Підвіконня", "Раковина", "Сайт", "Розмір", "Шкіра", "Пропустити",
            "Спідниця", "Сани", "Ковзати", "Слот", "Слимак", "Посмішка", "Дим", "Равлик", "Змія",
            "Клацання", "Мило", "Газована вода", "Диван", "М'який", "Грунт", "Продано", "Підошва",
            "Син", "Сорт", "Душа", "Суп", "Свиноматка", "Спа", "Простір", "Лопата", "Діапазон",
            "Іскра", "Спис", "Швидкість", "Заклинання", "Спеція", "Обертання", "Плювати", "Пляма", "Спрей", "Шпора",
            "Шпигун", "Квадрат", "Сцена", "Сходи", "Марка", "Стенд", "Витріщатися", "Старт", "Штат",
            "Залишитися", "Пара", "Сталь", "Стебло", "Крок", "Рагу", "Жало", "Мішати", "Акція",
            "Шторм", "Історія", "Плита", "Солома", "Потік", "Струна",
            "Смуга", "Вчитися", "Речі", "Пень", "Стиль", "Костюм", "Літо", "Прибій", "Лебідь",
            "Плавати", "Гойдалка", "Перемикач", "Меч", "Кнопка", "Тег", "Розмова", "Високий",
            "Танк", "Стрічка", "Дьоготь", "Пиріг", "Завдання", "Смак", "Податок", "Команда",
            "Сльоза", "Зуби", "Розповідь", "Термін", "Тест", "Текст", "Відлига", "Річ", "Думати",
            "Тонкий", "Стринги", "Шип", "Нитка", "Великий палець", "Кліщ", "Краватка", "Плитка", "Каса",
            "Олово", "Чайові", "Шина", "Назва", "Жаба", "Тост", "Праця", "Жетон",
            "Мито", "Тон", "Інструмент", "Зуб", "Топ", "Факел", "Кидати", "Дотик", "Тур", "Рушник",
            "Вежа", "Трек", "Торгівля", "Слід", "Трамвай", "Пастка", "Таця",
            "Похід", "Трюк", "Подорож", "Війська", "Правда", "Трубка", "Ванна", "Буксир",
            "Мелодія", "Дерн", "Поворот", "Бивень", "Близнюк", "Тип", "Блок", "Урна", "Використання", "Фургон",
            "Ваза", "Вуаль", "Вена", "Вентиляція", "Дієслово", "Жилет", "Ветеринар", "Порок", "Вид", "Лоза",
            "Голос", "Пустота", "Вольт", "Голосування", "Клятва", "Зарплата", "Вагон", "Талія", "Чекати", "Прокидатися",
            "Паличка", "Хочу", "Війна", "Палата", "Теплий", "Попереджати", "Основа", "Мити",
            "Оса", "Хвиля", "Віск", "Слабкий", "Багатство", "Носити", "Павутина",
            "Клин", "Бур'ян", "Тиждень", "Добре", "Захід", "Мокрий", "Кит", "Причал", "Пшениця", "Колесо",
            "Батіг", "Білий", "Цілий", "Гніт", "Дружина", "Перука", "Дикий", "Воля", "Вино",
            "Підморгувати", "Дріт", "Мудрий", "Бажання", "Розум",
            "Черв'як", "Обгортка", "Зап'ястя", "Питати", "Неправильно", "Пряжа",
            "Кричати", "Жовтий", "Вереск", "Жовток", "Зона",
             # Adding more common easy words
            "Камера", "Радіо", "Відео", "Піаніно", "Скрипка", "Гітара", "Флейта", "Труба",
            "Олівець", "Гумка", "Лінійка", "Папір", "Папка", "Зошит", "Школа", "Вчитель", "Учень",
            "Лікар", "Медсестра", "Поліція", "Пожежник", "Художник", "Пекар", "Водій", "Фермер",
            "Панда", "Коала", "Зебра", "Верблюд", "Мавпа", "Горила", "Акула", "Дельфін",
            "Орел", "Папуга", "Голуб", "Індичка", "Пінгвін", "Страус", "Павук", "Ящірка",
            "Черепаха", "Хом'як", "Цуценя", "Кошеня",
            "Кухня", "Спальня", "Ванна кімната", "Гараж", "Паркан", "Стежка",
            "Тарілка", "Виделка", "Ложка", "Ніж", "Склянка", "Пляшка", "Серветка",
            "Шафа", "Диван", "Крісло", "Ковдра", "Подушка",
            "Брат", "Сестра", "Мама", "Тато", "Бабуся", "Дідусь", "Друг",
            "Весна", "Літо", "Осінь", "Зима", "Ранок", "Вечір", "День",
            "Понеділок", "Вівторок", "Середа", "Четвер", "П'ятниця", "Субота", "Неділя",
            "Січень", "Лютий", "Березень", "Квітень", "Травень", "Червень",
            "Липень", "Серпень", "Вересень", "Жовтень", "Листопад", "Грудень",
            "Північ", "Південь", "Колір", "Чорний", "Зелений", "Коричневий", "Фіолетовий",
            "Один", "Два", "Три", "Чотири", "П'ять", "Шість", "Сім", "Вісім", "Дев'ять", "Десять",
            "Одинадцять", "Дванадцять", "Сто", "Тисяча", "Мільйон",
            "Сорочка", "Штани", "Сукня", "Черевики", "Капелюх", "Пальто", "Окуляри"
        ],
        "Звичайні": [
            "Велосипед", "Яблуко", "Банан", "Виноград", "Апельсин", "Лев", "Тигр", "Ведмідь", "Слон", "Жирафа",
            "Пілот", "Сантехнік", "Офіціант", "Актор", "Суддя", "Юрист", "Охоронець", "Шеф-кухар", "Тренер", "Гід",
            "Аеропорт", "Вокзал", "Ринок", "Міст", "Кінотеатр", "Готель", "Музей", "Палац", "В'язниця", "Школа",
            "Теніс", "Футбол", "Хокей", "Регбі", "Гольф", "Лижі", "Бокс", "Дзюдо", "Бінго", "Шахи",
            "Абрикос", "Авокадо", "Вишня", "Кокос", "Інжир", "Ківі", "Лимон", "Манго", "Диня", "Оливка",
            "Персик", "Груша", "Слива", "Ягода", "Помідор", "Морква", "Цибуля", "Картопля", "Кукурудза", "Горох",
            "Зима", "Весна", "Літо", "Осінь", "Шторм", "Грім", "Хмара", "Дощ", "Сніг", "Вітер",
            "Понеділок", "П'ятниця", "Неділя", "Квітень", "Серпень", "Місяць", "Тиждень", "Рік", "Година", "Хвилина",
            "Коло", "Квадрат", "Зірка", "Серце", "Хрест", "Лінія", "Точка", "Фігура", "Кут", "Крива",
            "Якір", "Ковадло", "Арка", "Стріла", "Атом", "Значок", "Бублик", "Банджо", "Барон", "Басейн",
            "Партія", "Жезл", "Мензурка", "Борода", "Звір", "Жук", "Лавка", "Ягода", "Бісквіт", "Лезо",
            "Відбілювач", "Сліпий", "Блаженство", "Блок", "Кров", "Цвітіння", "Дошка", "Хвастощі", "Боббі", "Бойлер",
            "Бонус", "Підвищення", "Кабінка", "Здобич", "Кордон", "Ботаніка", "Пляшка", "Дно", "Гілка", "Щедрість",
            "Кишечник", "Скоба", "Мозок", "Гальмо", "Бренд", "Латунь", "Хоробрий", "Ширина", "Перерва", "Груди",
            "Порода", "Бриз", "Варити", "Хабар", "Цегла", "Наречена", "Міст", "Короткий", "Розсіл", "Широкий",
            "Смажити", "Бронза", "Струмок", "Мітла", "Бульйон", "Коричневий", "Синець", "Щітка", "Звір", "Біль",
            "Відро", "Пряжка", "Бюджет", "Буфер", "Буфет", "Коляска", "Цибулина", "Випуклість", "Куля", "Зв'язка",
            "Кролик", "Бюро", "Поховання", "Пальник", "Бушель", "Дворецький", "Масло", "Кнопка", "Покупець", "Кабіна",
            "Кабель", "Кактус", "Скринька", "Курсант", "Верблюд", "Камера", "Канал", "Канарка", "Відвертий", "Свічка",
            "Каное", "Навіс", "Кантон", "Полотно", "Каньйон", "Столиця", "Карат", "Вуглець", "Вантаж", "Колядка",
            "Килим", "Картон", "Різьблення", "Замок", "Випадковий", "Худоба", "Причина", "Кедр", "Підвал", "Цемент",
            "Перепис", "Каша", "Ланцюг", "Крейда", "Спів", "Хаос", "Каплиця", "Чарівність", "Діаграма", "Погоня",
            "Прірва", "Дешевий", "Обман", "Перевірка", "Щока", "Підбадьорювати", "Сир", "Вишня", "Скриня", "Курча",
            "Шеф", "Дитина", "Холод", "Дзвін", "Китай", "Чіп", "Хор", "Задихатися", "Акорд", "Робота по дому",
            "Шматок", "Маслоробка", "Жолоб", "Сидр", "Сигара", "Попруга", "Коло", "Цирк", "Цивільний", "Претензія",
            "Затискач", "Молюск", "Брязкіт", "Гуркіт", "Зіткнення", "Застібка", "Клас", "Пунк", "Кіготь", "Глина",
            "Чистий", "Ясний", "Шип", "Ущелина", "Клерк", "Клік", "Скеля", "Підйом", "Клініка", "Плащ",
            "Годинник", "Груда", "Сабо", "Закрити", "Тканина", "Хмара", "Вплив", "Гвоздика", "Клоун", "Клуб",
            "Квоктати", "Група", "Тренер", "Узбережжя", "Павутина", "Какао", "Кава", "Котушка", "Монета", "Холод",
            "Комір", "Двокрапка", "Колір", "Лоша", "Гребінець", "Приходити", "Комета", "Комік", "Кома", "Раковина",
            "Конус", "Кухар", "Прохолодний", "Курник", "Справлятися", "Мідь", "Копія", "Корал", "Шнур", "Ядро",
            "Корок", "Кукурудза", "Кут", "Труп", "Вартість", "Диван", "Кашель", "Рахувати", "Купе", "Купон",
            "Суд", "Обкладинка", "Боягуз", "Краб", "Тріщина", "Ремесло", "Журавль", "Кривошип", "Аварія", "Ящик",
            "Повзати", "Божевілля", "Божевільний", "Вершки", "Створити", "Кредит", "Струмок", "Повзти", "Гребінь", "Екіпаж",
            "Ліжечко", "Злочин", "Хрусткий", "Критик", "Каркати", "Глечик", "Шахрай", "Урожай", "Хрест", "Натовп",
            "Корона", "Сирий", "Жорстокий", "Круїз", "Крихта", "Розчавити", "Коринка", "Милиця", "Склеп", "Куб",
            "Зозуля", "Манжета", "Культ", "Купідон", "Бордюр", "Ліки", "Сувенір", "Локон", "Каррі", "Прокляття",
            "Крива", "Цикл", "Цинік", "Молочний", "Маргаритка", "Танець", "Денді", "Небезпека", "Сміливий", "Темний",
            "Дротик", "Тире", "Дані", "Дата", "Світанок", "Заціпеніння", "Мертвий", "Глухий", "Угода", "Декан",
            "Дорогий", "Дебати", "Дебет", "Борг", "Дебют", "Декада", "Розпад", "Палуба", "Декор", "Приманка",
            "Вчинок", "Глибокий", "Олень", "Поразка", "Дефект", "Ступінь", "Затримка", "Захоплення", "Долина", "Дельта",
            "Попит", "Демон", "Джинс", "Вм'ятина", "Депо", "Глибина", "Заступник", "Дербі", "Пустеля", "Дизайн",
            "Бажання", "Стіл", "Деталь", "Виявляти", "Пристрій", "Диявол", "Циферблат", "Щоденник", "Гральні кістки", "Дієта",
            "Цифра", "Обідати", "Шлюпка", "Вечеря", "Діод", "Бруд", "Диск", "Страва", "Диск", "Кювет",
            "Пісенька", "Диван", "Дайвер", "Док", "Лікар", "Ухилятися", "Догма", "Серветка", "Робити", "Долар",
            "Лялька", "Дельфін", "Домен", "Купол", "Донор", "Загибель", "Двері", "Допінг", "Доза", "Крапка",
            "Подвійний", "Сумнів", "Тісто", "Голуб", "Вниз", "Дюжина", "Чернетка", "Перетягувати", "Злив", "Качур",
            "Драма", "Штора", "Малювати", "Страх", "Мрія", "Сукня", "Дрейф", "Дриль", "Напій", "Крапля",
            "Водити", "Дрон", "Крапля", "Стадо", "Наркотик", "Барабан", "П'яний", "Сушарка", "Подвійний", "Качка",
            "Протока", "Дуель", "Дует", "Герцог", "Тупий", "Манекен", "Звалище", "Дюна", "Гній", "Сутінки",
            "Пил", "Голландська", "Обов'язок", "Гном", "Житло", "Барвник", "Вмираючий", "Динамо", "Орел", "Граф",
            "Рано", "Земля", "Легкість", "Мольберт", "Великдень", "Їсти", "Чорне дерево", "Відлуння", "Затемнення", "Край",
            "Редактор", "Ефект", "Зусилля", "Яйце", "Вісім", "Викидати", "Лікоть", "Старший", "Обирати", "Елегія",
            "Елемент", "Слон", "Одинадцять", "Ельф", "Еліта", "Лось", "В'яз", "Емблема", "Ембріон", "Наждак",
            "Емоція", "Імперія", "Порожній", "Емаль", "Кінець", "Ворог", "Енергія", "Двигун", "Насолоджуватися", "Прапорщик",
            "Входити", "Вхід", "Посланник", "Заздрість", "Епос", "Епоха", "Рівний", "Екватор", "Ера", "Гумка",
            "Помилка", "Есе", "Маєток", "Ефір", "Етика", "Етнічний", "Подія", "Зло", "Іспит", "Вихід",
            "Експерт", "Експорт", "Око", "Байка", "Обличчя", "Факт", "Фактор", "Зникати", "Зазнати невдачі", "Слабкий",
            "Ярмарок", "Фея", "Віра", "Підробка", "Сокіл", "Осінь", "Брехня", "Слава", "Сім'я", "Голод",
            "Вентилятор", "Уява", "Ікло", "Фарс", "Ферма", "Швидкий", "Жир", "Доля", "Батько", "Кран",
            "Провина", "Ласка", "Оленя", "Страх", "Свято", "Подвиг", "Відчувати", "Ноги", "Злочинець", "Повсть",
            "Жінка", "Паркан", "Пором", "Принести", "Плід", "Лихоманка", "Волокно", "Волокно", "Скрипка", "Поле",
            "Злодій", "Свистун", "П'ятдесят", "Інжир", "Бійка", "Фігура", "Файл", "Заповнити", "Фільм", "Фільтр",
            "Бруд", "Фінал", "Фінанси", "Знайти", "Штраф", "Палець", "Фініш", "Вогонь", "Фірма", "Перший",
            "Риба", "Кулак", "П'ять", "Виправити", "Прапор", "Ціп", "Чуття", "Лусочка", "Полум'я", "Фланг",
            "Спалах", "Спалах", "Колба", "Плоский", "Смак", "Вада", "Блоха", "Пляма", "Флот", "Плоть",
            "Гнучкий", "Клацання", "Політ", "Кремінь", "Переворот", "Флірт", "Поплавок", "Зграя", "Повінь", "Підлога",
            "Провал", "Флора", "Нитка", "Борошно", "Потік", "Квітка", "Вільний", "Пух", "Рідина", "Змив",
            "Флейта", "Муха", "Піна", "Фокусний", "Фокус", "Туман", "Фольга",
            "Галактика", "Галерея", "Галоп", "Азартна гра", "Гра", "Банда", "Розрив", "Гараж", "Сад", "Часник",
            "Газ", "Ворота", "Збирати", "Марля", "Погляд", "Шестерня", "Дорогоцінний камінь", "Ген", "Генерал", "Джин",
            "Геній", "Жанр", "Ніжний", "Джентльмен", "Жест", "Привид", "Гігант", "Дар", "Хіхікати", "Зябра",
            "Імбир", "Дівчина", "Дарувати", "Льодовик", "Радий", "Галявина", "Погляд", "Залоза", "Скло", "Блиск",
            "Глайдер", "Проблиск", "Глобус", "Морок", "Слава", "Глянець", "Рукавичка", "Світитися", "Клей", "Гном",
            "Йти", "Ціль", "Коза", "Бог", "Золото", "Гольф", "Пішов", "Хороший", "Гусак", "Ущелина",
            "Євангеліє", "Плітки", "Губернатор", "Хапати", "Грація", "Клас", "Зерно", "Грам", "Граматика", "Гранд",
            "Грант", "Виноград", "Графік", "Схопити", "Трава", "Могила", "Гравій", "Соус", "Сірий", "Пастися",
            "Мастило", "Великий", "Жадібність", "Зелений", "Вітати", "Сітка", "Скорбота", "Гриль", "Похмурий", "Посмішка",
            "Захват", "Виття", "Бакалія", "Пах", "Наречений", "Паз", "Земля", "Група", "Гай", "Рости",
            "Гарчання", "Ріст", "Личинка", "Образа", "Охоронець", "Вгадати", "Гість", "Гід", "Гільдія", "Провина",
            "Гітара", "Затока", "Чайка", "Десна", "Пістолет", "Порив", "Жолоб", "Хлопець", "Тренажерний зал", "Звичка",
            "Злом", "Град", "Волосся", "Половина", "Зал", "Ореол", "Зупинка", "Шинка", "Молоток", "Рука",
            "Зручний", "Повісити", "Ангар", "Щасливий", "Гавань", "Важкий", "Заєць", "Шкода", "Арфа", "Жорсткий",
            "Суворий", "Урожай", "Хеш", "Поспіх", "Люк", "Ненависть", "Тягнути", "Притулок", "Яструб", "Сіно",
            "Небезпека", "Димка", "Ліщина", "Голова", "Зцілювати", "Здоров'я", "Купа", "Чути", "Почути", "Серце",
            "Тепло", "Верес", "Важкий", "Огорожа", "П'ята", "Зріст", "Спадкоємець", "Пекло", "Шолом", "Допомога",
            "Поділ", "Курка", "Звідси", "Вона", "Трава", "Стадо", "Тут", "Герой", "Оселедець", "Її",
            "Сховати", "Високий", "Пагорб", "Пагорб", "Заважати", "Шарнір", "Підказка", "Стегно", "Оренда", "Шипіння",
            "Хіт", "Вулик", "Скарб", "Хобі", "Хокей", "Тримати", "Діра", "Свято", "Порожній", "Святий",
            "Дім", "Чесний", "Мед", "Капюшон", "Гак", "Обруч", "Надія", "Ріг", "Жах", "Кінь",
            "Шланг", "Господар", "Гарячий", "Готель", "Собака", "Година", "Дім", "Зависати", "Як", "Виття",
            "Обійми", "Величезний", "Корпус", "Гул", "Людина", "Смиренний", "Гумор", "Горб", "Голод", "Полювання",
            "Біль", "Хатина", "Гібрид", "Гідра", "Гімн", "Ікона", "Ідея", "Ідол", "Іглу", "Образ",
            "Поштовх", "Дюйм", "Індекс", "Чорнило", "Корчма", "Комаха", "Залізо", "Острів", "Свербіж", "Пункт",
            "Слонова кістка", "Плющ", "Джек", "В'язниця", "Джем", "Банка", "Щелепа", "Джаз", "Джинси", "Джип",
            "Желе", "Струмінь", "Драгоцінний камінь", "Джиг", "Робота", "Приєднатися", "Жарт", "Напрямок", "Радість", "Суддя",
            "Глечик", "Сік", "Стрибок", "Червень", "Журі", "Просто", "Джут", "Кіль", "Тримати", "Кег", "Ламінарія",
            "Зберігати", "Чайник", "Ключ", "Удар", "Дитина", "Вбивати", "Пекти", "Кін", "Добрий", "Король",
            "Поцілунок", "Набір", "Повітряний змій", "Коліно", "Лицар", "В'язати", "Ручка", "Стук", "Вузол", "Знати",
            "Лейбл", "Мереживо", "Відсутність", "Леді", "Озеро", "Лампа", "Земля", "Провулок", "Коліна", "Жайворонок",
            "Лазер", "Останній", "Пізно", "Промивати", "Закон", "Газон", "Лінивий", "Свинець", "Лист", "Витік",
            "Худий", "Стрибок", "Вчитися", "Оренда", "Покидати", "Лекція", "Зліва", "Нога", "Легенда", "Лимон",
            "Позичати", "Лінза", "Сочевиця", "Менше", "Урок", "Дозволяти", "Лист", "Рівень", "Важіль", "Брехун",
            "Ліберал", "Північ"
        ],
        "Складні": [
            "Комп'ютер", "Телефон", "Годинник", "Окуляри", "Підводний човен", "Вертоліт", "Ракета", "Космічний корабель", "Парашут", "Сноуборд",
            "Алгоритм", "Рюкзак", "Бинт", "Батарея", "Бісквіт", "Ковдра", "Блендер", "Блузка", "Відро", "Ґудзик",
            "Кабінет", "Кактус", "Камера", "Свічка", "Полотно", "Килим", "Морква", "Замок", "Стеля", "Цемент",
            "Кераміка", "Канал", "Коло", "Цирк", "Клієнт", "Клімат", "Шафа", "Кава", "Труна", "Комір",
            "Комедія", "Комфорт", "Здійснювати", "Спільний", "Компас", "Концерт", "Концепція", "Бетон", "Проведити", "Конфлікт",
            "Конгрес", "Контекст", "Контроль", "Конвертувати", "Кут", "Бавовна", "Рада", "Лічильник", "Країна", "Пара",
            "Сміливість", "Курс", "Кузен", "Кредит", "Цвіркун", "Кристал", "Культура", "Завіса", "Подушка", "Звичай",
            "Пошкодження", "Небезпека", "Дилер", "Дебати", "Декада", "Ступінь", "Попит", "Дизайн", "Деталь", "Пристрій",
            "Діамант", "Дайджест", "Вечеря", "Прямий", "Лікар", "Долар", "Домен", "Віслюк", "Подвійний", "Дракон",
            "Шухляда", "Малюнок", "Водій", "Завзяття", "Видання", "Ефект", "Зусилля", "Восьмий", "Еластичний", "Вибори",
            "Елемент", "Посольство", "Емоція", "Імперія", "Двигун", "Досить", "Сутність", "Вхід", "Епізод", "Екватор",
            "Сутність", "Маєток", "Вечір", "Докази", "Приклад", "Обмін", "Виправдання", "Експонат", "Витрати", "Експерт",
            "Експрес", "Розширити", "Тканина", "Фактор", "Фабрика", "Невдача", "Сім'я", "Відомий", "Фантазія", "Фермер",
            "Мода", "Батько", "Втома", "Кран", "Особливість", "Федеральний", "Відчуття", "Товариш", "Крило", "Фантастика",
            "Фігура", "Фільтр", "Фінанси", "Фініш", "Пожежник", "Фіскальний", "Риболовля", "Фітнес", "Смак", "Політ",
            "Квітка", "Літаючий", "Слідувати", "Ліс", "Формальний", "Формат", "Колишній", "Формула", "Фортуна", "Вперед",
            "Засновник", "Четвертий", "Крихкий", "Фрагмент", "Свобода", "Морозильна камера", "Вантаж", "Французька", "Друг", "Бахрома",
            "Заморожений", "Смеження", "Функція", "Похорон", "Піч", "Майбутнє", "Галерея", "Галон", "Гараж", "Сміття",
            "Сад", "Часник", "Збирати", "Стать", "Генерал", "Геній", "Ніжний", "Німецький", "Жест", "Гігантський",
            "Хіхікати", "Імбир", "Жирафа", "Льодовик", "Гламур", "Погляд", "Окуляри", "Глобальний", "Глюкоза", "Золотий",
            "Євангеліє", "Плітки", "Керувати", "Поступовий", "Граматика", "Дідусь", "Бабуся", "Виноград", "Графічний", "Гравій",
            "Соус", "Жир", "Більший", "Зелений", "Бакалія", "Земля", "Група", "Зростання", "Провина", "Гітара",
            "Звичка", "Молоток", "Хом'як", "Жменя", "Ручка", "Вішалка", "Траплятися", "Гавань", "Ледве", "Урожай",
            "Небезпека", "Здоров'я", "Небеса", "Висота", "Шолом", "Помічник", "Трав'яний", "Героїчний", "Прихований", "Високий",
            "Виділяти", "Шосе", "Похід", "Історія", "Хокей", "Тримач", "Порожній", "Чесний", "Мед", "Честь",
            "Жах", "Кінь", "Лікарня", "Гуртожиток", "Готель", "Натовп", "Гуманний", "Людина", "Скромний", "Вологість",
            "Гумор", "Голод", "Мисливець", "Перешкода", "Чоловік", "Гібрид", "Гігієна", "Дефіс", "Айсберг", "Бурулька",
            "Значок", "Ідея", "Ідеальний", "Ідіома", "Іглу", "Ігнорувати", "Зображення", "Вплив", "Імпорт", "Дохід",
            "Індекс", "Кімнатний", "Спонукати", "Немовля", "Інфікувати", "Робити висновок", "Приплив", "Інформувати", "Травма", "Внутрішній",
            "Ввід", "Комаха", "Всередині", "Образити", "Застрахувати", "Неушкоджений", "Намір", "Винаходити", "Інвестувати", "Запросити",
            "Іронія", "Острів", "Проблема", "Слонова кістка", "Куртка", "Ягуар", "Жаргон", "Жасмин", "Яшма", "Спис",
            "Щелепа", "Ревнивий", "Джерсі", "Коштовність", "Пазл", "Дзвін", "Жокей", "Біг підтюпцем", "Журнал", "Подорож",
            "Життєрадісний", "Радісний", "Судимий", "Судовий", "Жонглер", "Сік", "Плутанина", "Джемпер", "Джунглі", "Молодший",
            "Юпітер", "Справедливість", "Виправдовувати", "Карма", "Каяк", "Хранитель", "Розплідник", "Чайник", "Клавіатура", "Хакі",
            "Викрадати", "Нирка", "Вбивця", "Вбивство", "Запалювати", "Королівство", "Кіоск", "Кошеня", "Вправність", "Рюкзак",
            "Лицар", "В'язання", "Стук", "Коала", "Етикетка", "Праця", "Драбина", "Лагуна", "Ягня", "Земля",
            "Посадка", "Ліхтар", "Ноутбук", "Великий", "Лазер", "Останнім часом", "Прихований", "Останній", "Токарний верстат", "Латинська",
            "Останній", "Сміх", "Запуск", "Прання", "Лавр", "Лаванда", "Щедрий", "Законний", "Позов", "Юрист",
            "Макет", "Лідер", "Ліга", "Дірявий", "Вчитися", "Оренда", "Шкіра", "Залишати", "Лекція", "Головна книга",
            "Легенда", "Легіон", "Лимон", "Довжина", "Лінза", "Леопард", "Урок", "Смертельний", "Лист", "Рівень",
            "Важіль", "Відповідальний", "Брехун", "Наклеп", "Вільний", "Лібідо", "Бібліотека", "Ліцензія", "Ліцензія", "Лишайник",
            "Світло", "Ймовірно", "Бузок", "Ліміт", "Льон", "Затримуватися", "Лінгвіст", "Підкладка", "Пов'язаний", "Коноплянка",
            "Рідина", "Лікер", "Слухати", "Буквальний", "Літій", "Сміття", "Маленький", "Жвавий", "Печінка", "Життя",
            "Ящірка", "Лама", "Завантаження", "Ненавидіти", "Лобі", "Омар", "Місцевий", "Знаходити", "Арешт", "Сарана",
            "Ложа", "Журнал", "Лісоруб", "Логіка", "Самотній", "Довше", "Спостереження", "Послабити", "Мародер", "Лорд",
            "Вантажівка", "Невдаха", "Втрата", "Лосьйон", "Лотерея", "лотос", "Голосніше", "Лаунж", "Воша", "Паршивий",
            "Коханець", "Нижче", "Лояльний", "Ясний", "Щасливий", "Пиломатеріали", "Горбистий", "Божевілля", "Місячний", "Обід",
            "Легеня", "Похитуватися", "Приманка", "Моторошний", "Ховатися", "Блиск", "Розкіш", "Лірика", "Машина", "Макро",
            "Мадам", "Шалено", "Мафія", "Магія", "Магма", "Магніт", "Сорока", "Діва", "Поштова скринька", "В основному",
            "Майор", "Виробник", "Макіяж", "Мамбо", "Ссавець", "Керувати", "Гриви", "Ясла", "Манія", "Маніакальний",
            "Садиба", "Мантія", "Керівництво", "Гній", "Клен", "Мармур", "Березень", "Маржа", "Марина", "Морський",
            "Маркер", "Ринок", "Марлін", "Кістковий мозок", "Болото", "Куниця", "Стриж", "Мученик", "Диво", "Талісман",
            "Муляр", "Маска", "Маси", "Майстер", "Мастика", "Матч", "Товариш", "Матриця", "Матрона", "Матерія",
            "Зрілий", "Максима", "Мер", "Луг", "Мізерний", "Значення", "Кір", "Міра", "Фрикаделька", "Механік",
            "Медаль", "Медіа", "Медик", "Середній", "Попурі", "М'який", "Мелодія", "Диня", "Член", "Пам'ять",
            "Загроза", "Лагодження", "Чорнороб", "Психічний", "Наставник", "Милосердя", "Злиття", "Заслуга", "Веселий", "Повідомлення",
            "Метал", "Метеор", "Лічильник", "Метод", "Метричний", "Метро", "Мікро", "Полудень", "Середній", "Карлик",
            "Північ", "Середина", "Могутність", "Могутній", "Мігрант", "Цвіль", "Пробіг", "Молочник", "Мільйон", "Міміка",
            "Фарш", "Мінден", "Шахтар", "Змішуватися", "Мінім", "Гірнича справа", "Неповнолітній", "М'ятний", "Мінус", "Хвилина",
            "Диво", "Дзеркало", "Бешкет", "Скнара", "Ракета", "Місія", "Помилка", "Пана", "Коханка", "Туманний",
            "Рукавиця", "Змішування", "Суміш", "Мобільний", "Модель", "Модем", "Сучасний", "Скромний", "Змінити", "Модуль",
            "Мохер", "Вологий", "Корінний зуб", "Ліпнина", "Молекула", "Момент", "Монарх", "Гроші", "Монітор", "Мавпа",
            "Моно", "Монстр", "Місяць", "Пам'ятник", "Настрій", "Місячний", "Моральний", "Бойовий дух", "Хворобливий", "Морг",
            "Ранок", "Ідіот", "Смертний", "Міномет", "Мозаїка", "Мечеть", "Моховитий", "Більшість", "Мотель", "Міль",
            "Мати", "Рух", "Мотив", "Мотор", "Девіз", "Курган", "Гора", "Тужити", "Миша", "Рот",
            "Рух", "Фільм", "Переміщення", "Косарка", "Слиз", "Брудний", "Мафін", "Глушити", "Душний", "Мульча",
             # Додавання більшої кількості складних українських слів для досягнення цілі 1000
            "Абстракція", "Авангард", "Автентичний", "Автобіографія", "Автономія", "Агрегат", "Адаптація", "Адреналін",
            "Академія", "Акваланг", "Акомпанемент", "Акробат", "Аксесуар", "Актуальний", "Акустика", "Алегорія",
            "Альтернатива", "Альтруїзм", "Амбіція", "Амбулаторія", "Амплітуда", "Ампутація", "Аналіз", "Аналогія",
            "Анатомія", "Анекдот", "Анестезія", "Аномалія", "Антагоніст", "Антена", "Антибіотик", "Антиквар",
            "Антипатія", "Антологія", "Антропологія", "Апартаменти", "Апатія", "Апеляція", "Апогей", "Апостол",
            "Апарат", "Аргумент", "Аристократ", "Арифметика", "Архіваріус", "Архіпелаг", "Архітектор", "Асиметрія",
            "Асистент", "Асоціація", "Асортимент", "Астероїд", "Астролог", "Астроном", "Асфальт", "Атмосфера",
            "Атрибут", "Аудиторія", "Аукціон", "Бактерія", "Баланс", "Балада", "Балет", "Барикада",
            "Барометр", "Басейн", "Батальйон", "Батарея", "Бібліографія", "Бібліотекар", "Біографія", "Біологія",
            "Біосфера", "Блазень", "Блокада", "Блокпост", "Бойкот", "Ботаніка", "Браслет", "Бригада",
            "Брошура", "Буржуазія", "Бюрократія", "Вакцина", "Вакцинація", "Валюта", "Вампір", "Вандалізм",
            "Варіант", "Варіація", "Вегетаріанець", "Велосипедист", "Вентилятор", "Вентиляція", "Вердикт", "Вертикаль",
            "Вестибюль", "Ветеран", "Ветеринар", "Вібрація", "Відеокамера", "Вікторина", "Вілла", "Віолончель",
            "Віртуоз", "Вірус", "Вітамін", "Вітрина", "Вокаліст", "Волонтер", "Вулкан", "Габарити",
            "Галактика", "Галерея", "Галстук", "Гардероб", "Гармонія", "Гастролі", "Гастрономія", "Генератор",
            "Генетика", "Географія", "Геологія", "Геометрія", "Гербарій", "Гербіцид", "Герметичний", "Гігієна",
            "Гідравліка", "Гідростанція", "Гімнастика", "Гіпербола", "Гіпноз", "Гіпотеза", "Гірлянда", "Гладіатор",
            "Глобалізація", "Глобус", "Горизонт", "Горизонталь", "Госпіталь", "Гравюра", "Градус", "Граматика",
            "Граніт", "Графік", "Графіка", "Грейпфрут", "Грип", "Гротеск", "Губернатор", "Гуманізм",
            "Дебати", "Дебют", "Девальвація", "Девіз", "Дегенерація", "Деградація", "Дегустація", "Дезінфекція",
            "Деккларація", "Декорація", "Делегація", "Делікатес", "Демократія", "Демонстрація", "Депресія", "Депутат",
            "Дерматолог", "Десерт", "Деструкція", "Детектив", "Дефіцит", "Деформація", "Діабет", "Діагноз",
            "Діагональ", "Діаграма", "Діалект", "Діалог", "Діамант", "Діапазон", "Дієта", "Диктатор",
            "Дилема", "Дилетант", "Динаміка", "Династія", "Диплом", "Дипломат", "Директор", "Диригент",
            "Дискусія", "Дисертація", "Дисципліна", "Дисплей", "Дистанція", "Дисципліна", "Добробут", "Догма",
            "Документ", "Долар", "Домінант", "Донор", "Досьє", "Доцент", "Драма", "Драматург"
        ],
        "довгі": ["Дегенерація", "Вегетаріанець", "Антропологія"]
    }
}
